apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx  # Ingress controller to handle the Ingress resources
  parameters:
    apiGroup: networking.k8s.io
    kind: IngressClassParams
    name: default