apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exp
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exp
spec:
  type: NodePort
  selector:
    app: log-output2-1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
