apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod-namespace
images:
- name: PROJECT/LOG-OUTPUT-IMAGE
  newName: gcr.io/dwk-gke-441712/log-output
  newTag: master-51d84d001f576617051e55a691a5c3236141a672
- name: PROJECT/PINGPONG-IMAGE
  newName: gcr.io/dwk-gke-441712/pingpong
  newTag: master-51d84d001f576617051e55a691a5c3236141a672
- name: PROJECT/TODO-APP-IMAGE
  newName: gcr.io/dwk-gke-441712/todo-app
  newTag: master-51d84d001f576617051e55a691a5c3236141a672
- name: PROJECT/TODO-BACKEND-IMAGE
  newName: gcr.io/dwk-gke-441712/todo-backend
  newTag: master-51d84d001f576617051e55a691a5c3236141a672
- name: PROJECT/TODO-CRON-IMAGE
  newName: gcr.io/dwk-gke-441712/todo-cron
  newTag: master-51d84d001f576617051e55a691a5c3236141a672
