apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod-namespace
images:
- name: PROJECT/LOG-OUTPUT-IMAGE
  newName: e
- name: PROJECT/PINGPONG-IMAGE
  newName: d
- name: PROJECT/TODO-APP-IMAGE
  newName: a
- name: PROJECT/TODO-BACKEND-IMAGE
  newName: b
- name: PROJECT/TODO-CRON-IMAGE
  newName: c
