apiVersion: batch/v1
kind: CronJob
metadata:
  name: reminder
spec:
  schedule: "0 * * * *"  # This runs the job every hour at the start of the hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: PROJECT/TODO-CRON-IMAGE
          restartPolicy: Never  # Run the job only once per scheduled time
