apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exp
spec:
  type: LoadBalancer
  selector:
    app: myapp5
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exp
spec:
  type: LoadBalancer
  selector:
    app: log-output2-1
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000