apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp6-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp6
  template:
    metadata:
      labels:
        app: myapp6
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: my-storage-claim
      containers:
        - name: myapp-write
          image: duchong/myapp:1.12
          imagePullPolicy: Always
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/public