apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 3/3.7/manifest/namespace.yaml
- 3/3.7/manifest/configMap.yaml
- 3/3.7/manifest/secret.yaml
- 3/3.7/manifest/statefulSet.yaml
- 3/3.7/manifest/deployment.yaml
- 3/3.7/manifest/service.yaml
- 3/3.7/manifest/cronjob.yaml
- 3/3.7/manifest/ingress.yaml
images:
- name: PROJECT/TODO-APP-IMAGE
  newName: duchong/todo-app:3.4
- name: PROJECT/TODO-BACKEND-IMAGE
  newName: duchong/todo-backend:3.41
- name: PROJECT/TODO-CRON-IMAGE
  newName: duchong/cronjob:3.73
namespace: project
