name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: dwk-environments
  SERVICE: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a sample script
        run: |
          echo "This is an experiment"
          echo "Running on $(uname -a)"
      # - uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # - name: 'Set up Cloud SDK'
      #   uses: google-github-actions/setup-gcloud@v2

      # - name: 'Use gcloud CLI'
      #   run: gcloud info